package com.geopdfviewer.android;

public enum TuzhiEnum {
    MESSURE_NONE_TYPE, MESSURE_DISTANCE_TYPE, MESSURE_AREA_TYPE,
    COORDINATE_DEFAULT_TYPE, COORDINATE_BLH_TYPE, COORDINATE_XYZ_TYPE,
    CENTERMODE, NOCENTERMODE,
    RED_LINE_QUERY, POI_QUERY,
    POI_DRAW_TYPE, TRAIL_DRAW_TYPE, NONE_DRAW_TYPE, LINE_DRAW_TYPE, SEARCH_DEMO,
    ZOOM_NONE, ZOOM_OUT, ZOOM_IN,
    NONE_FILE_TYPE, FILE_FILE_TYPE, ASSET_FILE_TYPE
}
